spring:
  application:
    name: users
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: Traktaryst
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
server:
  port: 8081
