spring:
  application:
    name: news
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: Traktaryst
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  cloud:
    openfeign:
      client:
        config:
          userClient:
            url: http://localhost:8081/users/
springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false
server:
  port: 8080
jwt:
  expiry-time: 600000
logging:
  level:
    org.springframework: error
    ru.clevertec: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /logs/news-api.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
      file-name-pattern: /logs/news-api.%d{yyyy-MM-dd}.%i.log