spring:
  application:
    name: news
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: Traktaryst
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  data:
    redis:
      port: 6379
  cloud:
    openfeign:
      client:
        config:
          userClient:
            url: http://localhost:8081/users/
springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        transaction: debug
        orm:
          jpa: debug
cache:
  algorithm: LFU
  capacity: 100
